#!/bin/bash
#SBATCH -p batch
#SBATCH -N 2
#SBATCH -n 14
#SBATCH -- mem 1000
#SBATCH -t 00:05:00
#SBATCH -J test-job
#SBATCH -o /home-mscluster/wstander/test.out
#SBATCH -e /home-mscluster/wstander/test.err
bash test14_cluster.sh
